[package]
name = "photo-cake-windows"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "photo_cake_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "photo-cake"
path = "src/main.rs"

[build-dependencies]
tauri-build = "2.6.3"

[dependencies]
tauri = "2.11.5"
serde.workspace = true
serde_json.workspace = true
photo-core = { path = "../../../crates/photo-core" }
